sudo: false

# xenial for newer docker-compose https://blog.travis-ci.com/2018-11-08-xenial-release
dist: xenial

matrix:
  include:
    - language: minimal
      install:
        - env | grep TRAVIS > .env
        - env | grep CI >> .env
        - chmod o+rw .
      before_script:
        # pull images so they're ready to run
        - docker-compose pull redis db elastic
        # build the containers so they're ready to run
        - docker-compose build web
        # warm up the app by creating the containers, network, etc but don't start anything yet
        # this ensures that everything is in place by the time wait-for-datastores.sh runs
        - docker-compose up --no-start
      script: docker-compose run web bash ./travis/py_tests.sh
      services:
        - docker
      env:
        name: Python

    - language: node_js
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      node_js:
        - "10.15.1"
      script: bash ./travis/js_tests.sh
      cache: yarn
      env:
        name: JavaScript
