version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - rest.action.multi.allow_explicit_index=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9101:9200"

  nginx:
    image: nginx
    ports:
      - "8063:8063"
    links:
      - web

  python:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/true
    environment:
      DEBUG: 'False'
      DEV_ENV: 'True'  # necessary to have nginx connect to web container
      NODE_ENV: 'production'
      PORT: 8061
      COVERAGE_DIR: htmlcov
      DATABASE_URL: postgres://postgres@db:5432/postgres
      OPEN_DISCUSSIONS_SECURE_SSL_REDIRECT: 'False'
      OPEN_DISCUSSIONS_DB_DISABLE_SSL: 'True'
      OPEN_DISCUSSIONS_REDDIT_URL: https://reddit.local
      OPEN_DISCUSSIONS_REDDIT_VALIDATE_SSL: 'False'
      OPEN_DISCUSSIONS_REDDIT_CLIENT_ID: od_client_id
      OPEN_DISCUSSIONS_REDDIT_SECRET: od_client_secret
      OPEN_DISCUSSIONS_FEATURES_DEFAULT: 'True'
      ELASTICSEARCH_URL: elastic:9200
      CELERY_TASK_ALWAYS_EAGER: 'False'
      CELERY_BROKER_URL: redis://redis:6379/4
      CELERY_RESULT_BACKEND: redis://redis:6379/4
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      WEBPACK_DEV_SERVER_HOST: ${WEBPACK_DEV_SERVER_HOST:-localhost}
      TIKA_SERVER_ENDPOINT: ${TIKA_SERVER_ENDPOINT:-http://tika:9998/}
      TIKA_CLIENT_ONLY: 'True'
    env_file: .env
    # set reddit.local in /etc/hosts
    extra_hosts:
      - "reddit.local:192.168.56.111"

  web:
    image: open_discussions_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3 &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py migrate --no-input &&
      python3 manage.py createcachetable &&
      uwsgi uwsgi.ini --honour-stdin'
    tty: true
    ports:
      - "8061:8061"
    links:
      - db
      - elastic
      - redis

  watch:
    build:
      context: .
      dockerfile: Dockerfile-node
    working_dir: /src
    command: >
      /bin/bash -c './webpack_dev_server.sh --install'
    ports:
      - "8062:8062"
    environment:
      NODE_ENV: 'production'
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      CONTAINER_NAME: 'watch'
    env_file: .env

  celery:
    image: open_discussions_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A open_discussions.celery:app worker -B -l ${OPEN_DISCUSSIONS_LOG_LEVEL:-INFO}'
    links:
      - db
      - redis

  tika:
    image: apache/tika:1.23
    entrypoint: java -jar tika-server-1.23.jar -h 0.0.0.0 -spawnChild
    ports:
      - "9998:9998"