# Generated by Django 2.1.15 on 2020-01-17 19:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0060_courserunfile")]

    operations = [
        migrations.AddField(
            model_name="bootcamp",
            name="raw_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningresourcerun",
            name="raw_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
