# Generated by Django 2.1.15 on 2020-01-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0061_courserunfile")]

    operations = [
        migrations.AlterModelOptions(
            name="courserunfile", options={"verbose_name": "courserunfile"}
        ),
        migrations.AlterField(
            model_name="courserunfile",
            name="key",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="courserunfile",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coursefiles",
                to="course_catalog.LearningResourceRun",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courserunfile", unique_together={("key", "run")}
        ),
    ]
