# Generated by Django 2.1.15 on 2020-01-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0061_move_raw_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserunfile',
            name='content_type',
            field=models.CharField(choices=[('file', 'file'), ('page', 'page')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='courserunfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserunfile',
            name='section',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='courserunfile',
            name='short_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courserunfile',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='courserunfile',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='courserunfile',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courserunfile',
            name='key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
