# Generated by Django 2.1.15 on 2020-01-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("course_catalog", "0062_alter_courserunfile")]

    operations = [
        migrations.AlterField(
            model_name="courserunfile",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courserun_files",
                to="course_catalog.LearningResourceRun",
            ),
        )
    ]
