# Generated by Django 2.1.15 on 2020-01-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0063_alter_courserunfile_again'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserunfile',
            old_name='full_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='courserunfile',
            name='phrases',
        ),
    ]
